config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/help', to:'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get "/login", to: "sessions#new"
  get '/signup', to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :booking
  resources :account_activations, only: [:edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

<div class="bg-white text-gray-900">
  <header class="flex justify-between items-center p-6">
    <div class="flex items-center space-x-2">
      <i class="fas fa-map-marker-alt text-gray-900"></i>
      <a href="/">
        <button class="flex items-center space-x-2 focus:outline-none">
          <img src="/wasedaplacelogo.png" alt="Logo" width="30" height="30" class="rounded-full">
          <span class="font-semibold text-xl">Waseda Place</span>
        </button>
      </a>
    </div>
    <a href="<%= booking_index_path %>">
      <%# <%= link_to "Book now", booking_index_path, class: "booking-top-button" %>
      <button class="booking-top-button">Book Now</button>
    </a>
  </header>
</div>

  <div class="container">
    <!-- <li><%= link_to "Home", root_path %></li> -->
    <!-- <li><%= link_to "Help", help_path %></li> -->
      <% if logged_in? %>
          <!-- <a href="#" id="account" class="dropdown-toggle"> -->
          <!--   Account <b class="caret"></b> -->
          <!-- </a> -->
        <ul id="dropdown-menu" class="">
          <li><%= link_to "Profile", current_user %></li>
          <!-- <li><%= link_to "Settings", edit_user_path(current_user) %></li> -->
          <li><%= link_to "Book", booking_index_path %></li>
          <!-- <li class="divider"></li> -->
          <li><%= link_to "Log out", logout_path, data: { "turbo": true, "turbo-method": :delete } %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
    <!-- </nav> -->
   </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
     <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>